alphagov/verify-saml-libs

saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepository.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepositoryTest.java
The same applies when fetching the signature trust engine.
=> firebreak: return Optional on fetching `MetadataResolver`

saml-security/src/main/java/uk/gov/ida/saml/security/MetadataBackedEncryptionCredentialResolver.java, saml-security/src/test/java/uk/gov/ida/saml/security/MetadataBackedEncryptionCredentialResolverTest.java
This is inline with how the other implementations are doing this and
will allow the applications to fail fast.
=> throw RuntimeException when no metadata cred is found

saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepository.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepositoryTest.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasTrustAnchorHealthCheckTest.java
The way that we recreate all resolvers then destroys the old one with the same names cause issues when trying to register metric. This change is to add a suffix with the current time in milliseconds.
=> BAU: Metadata resolvers for eIDAS trust anchors have unique suffix

saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/outbound/decorators/AbstractAssertionEncrypter.java, saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/outbound/decorators/SamlResponseAssertionEncrypter.java
Use the more generic EncryptionCredentialResolver in our encrypters so
that we can also use the MetadataEncryptionCredentialResolver for
resolving credentials.
=> bau: use EncryptionCredentialResolver in Encrypters

saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/TrustStorePathMetadataConfiguration.java
properties as the class is deprecated and hub will have new config items to support new truststores. Co-authored-by: Rachel Smith <rachel.smith@digital.cabinet-office.gov.uk>
=> BAU: Make TrustStorePathMetadataConfiguration ignore unknown json

build.gradle, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepository.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepositoryTest.java
- The eidas-trust-anchor lib now checks that all certs are valid.
- EidasMetadataResolverRepository now uses the earliest date of all certs instead
of the first cert.
Co-authored-by: Hoque Ali <hoque.ali@digital.cabinet-office.gov.uk>
Co-authored-by: Yancoba Thompson <yancoba.thompson@digital.cabinet-office.gov.uk>
=> EID-476 - Use latest Trust Anchor lib which now validate all x509 certs.

saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/CertificateChainValidationFilter.java, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/exception/EntityDescriptorListEmptyException.java, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/exception/KeyDescriptorListEmptyException.java, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/exception/RoleDescriptorListEmptyException.java
Exceptions are only for error reporting and handling and should not be used for other purposes like control flow.
Authors: @adityapahuja
=> BAU: Remove unnecessary exceptions from Certificate Chain Validation filter

saml-metadata-bindings-test/src/main/java/uk/gov/ida/saml/metadata/test/factories/metadata/EntityDescriptorFactory.java, saml-security/build.gradle, saml-security/src/main/java/uk/gov/ida/saml/security/MetadataBackedSignatureValidator.java, saml-security/src/test/java/uk/gov/ida/saml/security/MetadataBackedSignatureValidatorTest.java
Add an additional criterion to ensure only signing certificates are used for signature validation.
Co-Authored-by: Aditya Pahuja <aditya.pahuja@digital.cabinet-office.gov.uk>
=> BAU: Add UsageCriterion for signing to MetadataBackedSignatureValidator

saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/TrustStoreConfigurationTest.java, saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/AuthnContextFactory.java, saml-utils/src/test/java/uk/gov/ida/saml/core/transformers/AuthnContextFactoryTest.java
But wait, there's more:
- BAU Correctly encode paths in JSON tests
=> EID-625 Map eIDAS LoA High to Verify LoA 2

saml-utils/src/main/java/uk/gov/ida/saml/core/domain/MatchingDataset.java, saml-utils/src/main/java/uk/gov/ida/saml/core/domain/TransliterableMdsValue.java, saml-utils/src/main/java/uk/gov/ida/saml/core/test/builders/MatchingDatasetBuilder.java, saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/EidasMatchingDatasetUnmarshaller.java, saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/MatchingDatasetBuilder.java, saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/VerifyMatchingDatasetUnmarshaller.java, saml-utils/src/test/java/uk/gov/ida/saml/core/transformers/EidasMatchingDatasetUnmarshallerTest.java
We want to use a single MatchingDataset to represent all matching data
from both Verify and eIDAS. We need to allow for having non-latin script
values when handling eIDAS. This expands the MatchingDataset class (and
it's members) to allow it to store these values
=> EID-467: Use TransliterableMdsValue for names in MatchingDataset

build.gradle, build.jenkins, saml-extensions/build.gradle, saml-metadata-bindings-test/build.gradle, saml-metadata-bindings/build.gradle, saml-security/build.gradle, saml-serializers/build.gradle, saml-utils/build.gradle
The `bintray` plugin is a bit fussy about the `publications` key - it needs to point at `mavenJava` for the subproject, and I wasn't sure how to achieve this. Hence the duplication of the bintray block.
Hopefully should be simple enough.
=> Bau publish saml libs to bintray

.travis.yml, README.md, build.gradle
Bumps a few library versions to the recent builds which are available on bintray.
=> bau: Enable builds on Travis

build.gradle
Upgrade Dropwizard to 1.3.5 to fix various security issues.
Authors: @adityapahuja
=> 49: Upgrade Dropwizard to 1.3.5

saml-utils/src/main/java/uk/gov/ida/saml/core/test/AuthnResponseFactory.java
- Hub and Compliance tool use this factory for tests
- Hub should not depend on stub-idp-saml so move this
factory into a shared utils library
=> BAU: Move AuthnResponseFactory from stub-idp-saml

saml-extensions/src/main/java/uk/gov/ida/saml/core/EidasSecurityConfigurationInitializer.java, saml-extensions/src/main/resources/META-INF/org.opensaml.core.config.Initializer, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/PKIXSignatureValidationFilterProvider.java, saml-security/src/main/java/uk/gov/ida/saml/security/SignatureValidator.java
The eIDAS SAML Crypto specification allows only two cryptographic
algorithms to be used for signing SAML messages and metadata. One of
these (ECDSA) is already in the default OpenSAML
SignatureValidationConfiguration whitelist and just needed to be
whitelisted in `PKIXSignatureValidationFilterProvider` and
`SignatureValidator`. The other algorithm (RSASSA-PSS) is not in the
default OpenSAML whitelist and isn't supported natively by the Oracle
security providers.
The following changes are included:
- Add the BouncyCastle JCE Provider to the list of Java security
providers.
- Add an `EidasSecurityConfigurationInitializer` which uses the OpenSAML
`Initializer` interface and `InitializationService` mechanism to set
things up.
- Whitelist the RSASSA-PSS (sha256-rsa-MGF1) algorithm in …
=> EID-811: Add support for additional eIDAS signing algorithms

saml-security/src/main/java/uk/gov/ida/saml/security/signature/SignatureRSASSAPSS.java
-eidas crypto spec states that we should be supporting the RSASSA-PSS signature. This
isn't supplied by opensaml, so creating the signature object so we can
sign stub country assertion with this algorithm.
Co-authored-by: Simon Worthington <simon.worthington@digital.cabinet-office.gov.uk>
=> EID-835 - Create RSASSA-PSS signature to sign stub country

saml-utils/src/main/java/uk/gov/ida/saml/core/test/builders/AssertionBuilder.java
- As eidas can support multiple key transport algorithms, we want to be able to test that the hub can accept a response with each algorithm
- Will allow to build a saml response with a specific key transport algorithm
=> EID-820 - Specify key transport algorithm when building saml response

saml-security/src/main/java/uk/gov/ida/saml/security/SignatureFactory.java, saml-security/src/test/java/uk/gov/ida/saml/security/SignatureFactoryTest.java
- A NullCheck which was added means that it will never throw when
KeyInfo is required but a signing cert is not there.
- Change it so that if KeyInfo is required but a
signing cert is not present, then throw exception.
=> EID-939 - Fix test and SignatureFactory code

saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/EidasTrustAnchorHealthCheck.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasTrustAnchorHealthCheckTest.java
Healthcheck and unit tests now succeed when there are no trust anchors.
Changed healthcheck output to be more structured.
Returns details on each failure.
Co-authored-by: Simon Worthington <simon.worthington@digital.cabinet-office.gov.uk>
Co-authored-by: dbes-gds <daniel.besbrode@digital.cabinet-office.gov.uk>
=> BAU: Change test behaviour when no Eidas Metadata.

saml-utils/src/main/java/uk/gov/ida/saml/core/domain/OutboundResponseFromHub.java, saml-utils/src/main/java/uk/gov/ida/saml/core/test/builders/ResponseForHubBuilder.java
This will allow us to support the non-matching journey, where we will be sending out a response with the two assertions from the IDP, rather than a single assertion from the MDS.
https://trello.com/c/lKH7U7yW/185-wrap-assertions-in-hub-response-to-handle-idp-assertions
Solo: @alan-gds
=> lKH7U7yW: handle an arbitrary number of assertions

build.gradle, saml-extensions/src/main/java/uk/gov/ida/saml/core/EidasSecurityConfigurationInitializer.java, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/factories/CredentialResolverFactory.java, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/factories/MetadataSignatureTrustEngineFactory.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/PKIXSignatureValidationFilterProviderTest.java, saml-security/src/main/java/uk/gov/ida/saml/security/CredentialFactorySignatureValidator.java, saml-security/src/test/java/uk/gov/ida/saml/security/MetadataBackedEncryptionCredentialResolverTest.java, saml-security/src/test/java/uk/gov/ida/saml/security/MetadataBackedSignatureValidatorTest.java, saml-security/src/test/java/uk/gov/ida/saml/security/SignatureValidatorTest.java, saml-utils/src/main/java/uk/gov/ida/saml/core/domain/OutboundResponseFromHub.java, saml-utils/src/main/java/uk/gov/ida/saml/core/test/builders/ResponseForHubBuilder.java
Changes are:
- renaming of an imported classes package
- the PKIXSignatureValidationFilter now throws when it can't validate a signature (the exception is caught by the `MetadataResolver` so there's no noticable change to appication behaviour).
=> bau: upgrade to opensaml 3.4.0

saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/bundle/MetadataResolverBundle.java
This change will add a `MetadataHealthCheck` to the Dropwizard application when
you add a `MetadataResolverBundle`, instead of having to manually
build and register one.
=> BAU: Get MetadataResolverBundle to register MetadataHealthCheck

build.gradle, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepository.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepositoryTest.java
The MSA won't start if the trust anchor has an expired cert in it. This
is because the `EidasMetadataResolverRepository` throws an `Error` if
it finds an expired cert. This brings the app down.
This updates so that an Exception is thrown instead which is cauht and
handled, whilst logging. Sensu will pick up any expired certs.
=> EID-1072: Throw exception instead of error if expired cert

saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/bundle/MetadataResolverBundle.java, saml-metadata-bindings/src/main/java/uk/gov/ida/saml/metadata/exception/MetadataResolverCreationException.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/FederationMetadataBundleTest.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/FederationMetadataWithoutTrustStoresBundleTest.java
- We have multiple use cases where we might want to bind metadata or we
might not (non-matching - MSA, eIDAS - enabled/disabled)
- By only creating the resolve and healthcheck if the configuration
exists, we provide an easy way to "toggle" metadata
- Wrapped exceptions in new, more explicit exception but behaviour of "I
fall over at startup" is the same as before
Co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
=> BAU: Allow optional metadata bundling

build.gradle
The new version has mockito relocated to avoid version conflicts in
downstream packages.
=> BAU Bump trust-anchor to 1.0-53

build.gradle
Build 56 relocates the assertj package in the shadowJar. It was causing
a clash when imported into the hub with hub's own dependency on assertj.
=> BAU Bump trust anchor build to 56

build.gradle, saml-extensions/src/main/java/uk/gov/ida/saml/core/test/OpenSAMLMockitoRunner.java, saml-metadata-bindings/build.gradle, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasMetadataResolverRepositoryTest.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasTrustAnchorHealthCheckTest.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/EidasTrustAnchorResolverTest.java, saml-metadata-bindings/src/test/java/uk/gov/ida/saml/metadata/MetadataTrustStoreProviderTest.java, saml-serializers/src/test/java/uk/gov/ida/saml/deserializers/validators/Base64StringDecoderTest.java, saml-utils/src/test/java/uk/gov/ida/saml/core/transformers/outbound/decorators/ResponseSignatureCreatorTest.java, saml-utils/src/test/java/uk/gov/ida/saml/core/transformers/outbound/decorators/SamlResponseAssertionEncrypterTest.java, saml-utils/src/test/java/uk/gov/ida/saml/hub/validators/StringSizeValidatorTest.java
This pull request contains the following changes. 
* common-test-utils library is using latest version of mockito-core and is compatible with Java 11.
* Remove org.mockito:mockito-core:1.9.5 as this library is too old.
* Update all unit tests to use org.mockito.junit.MockitoJUnitRunner instead of org.mockito.runners.MockitoJUnitRunner since org.mockito.runners.MockitoJUnitRunner is deprecated.
* Replace org.mockito.Matchers.* with org.mockito.ArgumentMatchers.* since org.mockito.Matchers.* is deprecated.
* Resolve UnnecessaryStubbingException in unit tests.
* Refactor ResponseSignatureCreatorTest to get rid of duplicate code and NullPointerException and make it easy to read.
* Add jaxb library to resolve NoClassDefFoundError raised in EidasTrustAnchorResolverTest.
These changes are needed …
=> BAU: Update to use latest version of common-test-utils library

build.gradle
The new version of the security utils bump has the extra SLF4J removed.
=> Remove circular dependancy on trust anchor, and bump security utils.

saml-extensions/src/main/java/uk/gov/ida/saml/core/validation/errors/RequestFreshnessValidationSpecification.java
Fix this error showing up on sensu.
```
UNEXPECTED_EXCEPTION – {id: some_id, message: SAML Validation Specification: Request ID _some_id too old (request issueInstant 2019-01-10T17:28:10.082Z, current time 2019-01-10T11:47:09.766Z).
DocumentReference{documentName='Unspecified', documentSection='--'}}
```
=> Turned down old requests from error to warning.

saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/ResponseAttributesHashFactory.java, saml-utils/src/test/java/uk/gov/ida/saml/core/transformers/ResponseAttributesHashFactoryTest.java
- This HashFactory will be used in 2 scenarios 
Hub - To Hash the attributes of responses that are going back to the proxy node
Proxy Node - To Hash the attributes of the response from the Hub
- Check the Date format matches YYYY-MM-DD and throw if not
=> EID-1293 - Create HashFactory to hash certain attributes of the response

saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/EidasResponseAttributesHashLogger.java, saml-utils/src/test/java/uk/gov/ida/saml/core/transformers/EidasResponseAttributesHashLoggerTest.java
We should not clear out the entire MDC map for the current thread when we are finished logging our event.
=> Only clear out MDC properties set by this logger

build.gradle
Version 1.3.5 was vulnerable to a range of CVEs. Bumping to 1.3.9
alleviates this.
=> BAU Bump dropwizard_version to 1.3.9

saml-utils/src/main/java/uk/gov/ida/saml/core/transformers/EidasResponseAttributesHashLogger.java
After a review of user has logs with cyber, we agreed to change the names of MDC keys to:
eidasRequestId -> hubRequestId
eidasDestination -> destination
=> Renamed some MDC keys used for logging eIDAS user attributes hash

build.gradle
Build 179 bumped the version to 1.3.9. This caused an issue in the hub
with a bunch of integration tests which are hard to debug.
For the sake of progress with the proxy-node (which needs the hub to use
a build of saml-libs greater than 179) we're downgrading until we can
work out what's up with 1.3.9.
=> BAU Downgrade dropwizard to 1.3.8

saml-lib/src/main/java/uk/gov/ida/saml/hub/factories/UserIdHashFactory.java, saml-lib/src/test/java/uk/gov/ida/saml/hub/factories/UserIdHashFactoryTest.java
We need to hash the user's PID in saml-engine in the same way as we do
in the VSP for security logging purposes.
=> EIDAS: Copy VSP UserIdHashFactory

build.gradle
This has been prompted by a snyk alert in the proxy-node for a medium
risk vulnerability being brought in by the saml-lib package. It's a DoS
vulnerability in Jetty but is fixed by this bump.
This also brings the version inline with hub and proxy-node.
=> BAU Bump dropwizard to 1.3.9

saml-lib/src/main/java/uk/gov/ida/saml/core/domain/IdaMatchingServiceResponse.java, saml-lib/src/main/java/uk/gov/ida/saml/core/domain/MatchingServiceAuthnStatement.java, saml-lib/src/main/java/uk/gov/ida/saml/core/domain/SamlAttributeQueryAssertionEncrypter.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/assertion/AssertionAttributeStatementValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/assertion/AssertionValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/assertion/IdentityProviderAssertionValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/errors/SamlTransformationErrorFactory.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/subject/AssertionSubjectValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/subjectconfirmation/AssertionSubjectConfirmationValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/subjectconfirmation/BasicAssertionSubjectConfirmationValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/AttributeQueryToElementTransformer.java, saml-lib/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/SamlAttributeQueryAssertionSignatureSigner.java, saml-lib/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/SigningRequestAbstractTypeSignatureCreator.java, saml-lib/src/test/java/uk/gov/ida/saml/core/transformers/outbound/decorators/SamlAttributeQueryAssertionEncrypterTest.java, saml-lib/src/test/java/uk/gov/ida/saml/core/transformers/outbound/decorators/SamlAttributeQueryAssertionSignatureSignerTest.java, saml-lib/src/test/java/uk/gov/ida/saml/core/transformers/outbound/decorators/SigningRequestAbstractTypeSignatureCreatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/assertion/AssertionAttributeStatementValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/assertion/AssertionValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/assertion/IdentityProviderAssertionValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/subject/AssertionSubjectValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/subjectconfirmation/AssertionSubjectConfirmationValidatorTest.java, saml-test/src/main/java/uk/gov/ida/saml/core/test/HardCodedKeyStore.java, saml-test/src/main/java/uk/gov/ida/saml/core/test/builders/IdpFraudEventIdAttributeBuilder.java, saml-test/src/main/java/uk/gov/ida/saml/core/test/builders/VerifiedAttributeValueBuilder.java, saml-test/src/main/java/uk/gov/ida/saml/core/test/matchers/SignableSAMLObjectBaseMatcher.java, saml-test/src/main/java/uk/gov/ida/saml/core/test/validators/SingleCertificateSignatureValidator.java
- PR 1 of 3
- Move the SAML classes that are used by the MSA to a more appropriate shared location, so that the MSA does not have to pull in hub-saml.
=> bau - move msa SAML classes out of hub-saml

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/errors/SamlTransformationErrorFactory.java
Allow BearerSubjectConfirmationValidationSpecification to format the message correctly. String.format does not support '{0}'.
Fixes https://govuk.zendesk.com/agent/tickets/3661919
=> ZD3661919: Use correct format

.travis.yml, build.jenkins
`verify-saml-libs` is a library used in various Verify projects, like Hub and Proxy Node. We are migrating our Verify java runtimes off java8 and onto java11, for security reasons.
We want to build `verify-saml-libs` on OpenJDK 11 to mitigate any compile time vulnerabilities, and standardise to this java version.
To review:
* consider that the Jenkinsfile  `build.jenkins` now uses the Docker image `openjdk:11-jdk` to build the library, instead of `govukverify/java8:latest`.
* check the build completes successfully in Jenkins.
=> build verify-saml-libs with OpenJDK 11

.travis.yml, build.gradle
A project possibly compiled with java 1.8 (i.e. the `verify-matching-service-adapter`) will need to use `verify-saml-libs` compiled against java 1.8.
If not, the compiler will fail with a message like "class file has wrong version 55.0, should be 52.0".
This PR compiles `verify-saml-libs` using Java 1.8, and depends on  latest [verify-utils-libs](https://github.com/alphagov/verify-utils-libs/pull/34), also compiled using Java 1.8. 
To test, publish this branch to local maven repository, using `./gradlew clean publishToMavenLocal`.
Then, using the snapshot local version of verify-saml-libs published above run `./pre-commit.sh` on projects:
- verify-hub using openjdk-11
- verify-proxy-node using openjdk-11
- verify-matching-service-adapter using jdk 1.8
Then run …
=> ensure verify-saml-libs can be used by java 8 clients

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/assertion/AssertionValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/security/SamlAssertionsSignatureValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/security/SamlMessageSignatureValidator.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/assertion/AssertionValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/security/SamlAssertionsSignatureValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/security/SamlMessageSignatureValidatorTest.java
The eIDAS SAML profile does not require that attributes are signed. This
is different to the Verify profile which does require they are signed.
We will soon be onboarding a European country, Spain, that does not sign
its assertions. This will break saml-engine as well as the MSA.
This updates the `SamlMessageSignatureValidator` to make it possible to
skip signature validation if the message being validated is an eIDAS
attribute (determined by a flag when the validator is instantiated in
the apps).
If the attribute is signed (most countries do) we still validate that
signature and will raise if it fails - so we don't start allowing
invalid signatures. If the signature is not provided however, and the
flag is set, we just skip the validation.
=> EID-1504 Allow eIDAS assertions to be unsigned

build.gradle
It uses dropwizard 1.3.12 rather than 1.3.9 which has security issues.
=> BAU Upgrade ida_utils_version to 361

build.gradle, saml-lib/src/test/java/uk/gov/ida/saml/hub/factories/AttributeFactory_1_1Test.java
- Remove the unused jcentre from gradle
- Add back the import static org.assertj.jodatime.api.Assertions.assertThat which is being used
To fix https://verify-ci.ida.digital.cabinet-office.gov.uk/job/alphagov/job/verify-saml-libs/job/master/
=> Bau - Fix broken saml-lib jenkins job

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/errors/GenericHubProfileValidationSpecification.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/errors/SamlTransformationErrorFactory.java, saml-lib/src/main/java/uk/gov/ida/saml/deserializers/ElementToOpenSamlXMLObjectTransformer.java, saml-lib/src/main/java/uk/gov/ida/saml/deserializers/OpenSamlXMLObjectUnmarshaller.java, saml-lib/src/main/java/uk/gov/ida/saml/deserializers/validators/Base64StringDecoder.java, saml-lib/src/main/java/uk/gov/ida/saml/deserializers/validators/NotNullSamlStringValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/errors/SamlTransformationErrorFactory.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validation/errors/SamlTransformationErrorFactoryTest.java, saml-lib/src/test/java/uk/gov/ida/saml/deserializers/validators/Base64StringDecoderTest.java
Once every few months someone somewhere clicks the back button really quickly and generates an error in our logs; it's not really a problem and should probably be logged under WARN instead of ERROR.
Provide additional constructor for GenericHubProfileValidationSpecification that allows a Level to specified.
Use that constructor in uk.gov.ida.saml.core.validation.errors.SamlTransformationErrorFactory.duplicateMatchingDataset so that the Level is indeed WARN.
Write a test to make sure it happens.  Write a test for an arbitrary method to make sure it only happens for duplicateMatchingDataset.
Because the package names are out of sync with the folder structure, a lot of imports have changed thanks to the IDE.  Everything appears to still work despite this.
=> ZD-3570817 duplicate matching datasets

build.gradle
This change updates Wiremock library to use latest version. This change is needed for resolving Verify Test RP's integration test failures caused by Wiremock issues.
Author: @adityapahuja
=> AUTO-112: Update Wiremock library

saml-lib/src/test/java/uk/gov/ida/saml/security/saml/builders/ResponseBuilder.java, saml-test/src/main/java/uk/gov/ida/saml/core/test/builders/ResponseBuilder.java
New validations for request ids in verify-proxy-node require a minimum of 20 characters to be compliant with XML/SAML Ids.
=> update request ids for new validations, as used in verify-proxy-node

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/assertion/AssertionValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/security/SamlAssertionsSignatureValidator.java, saml-lib/src/main/java/uk/gov/ida/saml/security/SamlMessageSignatureValidator.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/assertion/AssertionValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/security/SamlAssertionsSignatureValidatorTest.java, saml-lib/src/test/java/uk/gov/ida/saml/security/SamlMessageSignatureValidatorTest.java
This reverts all the commits included in [PR #64](https://github.com/alphagov/verify-saml-libs/pull/64).
These files have not been altered in anyway since that PR so this
reversion doesn't affect other work.
This is being done due to a security issue with the approach and a new
implementation is being worked on.
=> Revert "EID-1504 Allow eIDAS assertions to be unsigned"

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/assertion/AssertionValidator.java
EID-1608 requires us to make the original SAML from the country available if the assertions are unsigned.  To determine whether an assertion is unsigned we can use the code that already exists in verify-saml-libs if we expose that functionality via a new public method.
So that's what we've done - say hello to `isAssertionUnsigned(Assertion)` - it does what it says on the tin (if the tin is made of its signature and by use of getter naming convention).
=> EID-1608 Check if assertions are unsigned

saml-lib/src/main/java/uk/gov/ida/saml/security/EidasValidatorFactory.java
There's a [PR here on the hub](https://github.com/alphagov/verify-hub/pull/367) to use this. That PR requires this to be merged.
The `EidasValidatorFactory` is used in the hub to validate the
signatures of SAML Responses and assertions from countries. We are going
to need to use this logic in the VSP and MSA as, due to countries not
signing assertions, the hub will be passing countries responses on to
the VSP/MSA without altering them.
The `EidasValidatorFactory` uses an `eidasMetadataResolverRepository`
which is responsible for fetching the countries trust anchors and
storing them in a trust store. The VSP and MSA will need to be
configured to do this.
=> EID-1603 Move EidasValidatorFactory to saml-lib

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/errors/GenericHubProfileValidationSpecification.java, saml-lib/src/main/java/uk/gov/ida/saml/security/AssertionDecrypter.java, saml-lib/src/main/java/uk/gov/ida/saml/security/SecretKeyEncrypter.java, saml-lib/src/main/java/uk/gov/ida/saml/security/errors/SamlTransformationErrorFactory.java, saml-lib/src/main/java/uk/gov/ida/saml/security/exception/SamlFailedToEncryptException.java, saml-lib/src/test/java/uk/gov/ida/saml/security/AssertionDecrypterTest.java, saml-lib/src/test/java/uk/gov/ida/saml/security/SecretKeyEncrypterTest.java, saml-lib/src/test/java/uk/gov/ida/saml/security/saml/TestCredentialFactory.java, saml-lib/src/test/java/uk/gov/ida/saml/security/saml/builders/ResponseBuilder.java
In order to maintain trust when receiving unsigned assertions we need to provide the original signed SAML message to the RP. The RP can only decrypt encrypted assertions if it has the symmetric key to do so but in the original SAML, it's encrypted for the hub so we need to decrypt the symmetric key(s) and re-encrypt it for the receiving RP and send it in a SAML form.  This PR takes care of the decryption / re-encryption of the symmetric key(s).
Add method to assertion decrypter to enable retrieval of encrypted symmetric keys.
Add class to encrypt the symmetric keys (known as secret keys) so the RP can un-encrypt them.
Add some exception handling so that the methods are consistent with the the rest of the library.  How that can be improved or altered is open to suggestions.
Follow the …
=> EID-1609 Re-encrypt symmetric key for receiving RP

saml-lib/src/main/java/uk/gov/ida/saml/core/IdaConstants.java, saml-lib/src/main/java/uk/gov/ida/saml/core/transformers/EidasUnsignedMatchingDatasetUnmarshaller.java, saml-lib/src/main/java/uk/gov/ida/saml/security/SecretKeyDecryptorFactory.java, saml-lib/src/test/java/uk/gov/ida/saml/core/transformers/EidasUnsignedMatchingDatasetUnmarshallerTest.java, saml-lib/src/test/java/uk/gov/ida/saml/security/SecretKeyDecryptorFactoryTest.java
Some EU Member States send unsigned SAML assertions from their Proxy Nodes.
The Verify Hub expects all assertions to be signed -  a [previous PR](https://github.com/alphagov/verify-saml-libs/pull/86) addresses this, by encrypting the ephemeral secret keys used to decrypt the assertions, using the service's public encryption key.
This PR will allow a Government Service to decrypt these assertions using its private encryption key. This code will be used by the [matching-service-adapter](https://github.com/alphagov/verify-matching-service-adapter) in a subsequent PR.
The key concept in this PR is that unsigned assertions will be first decrypted using the `EidasUnsignedMatchingDatasetUnmarshaller` and the actual creation of a `MatchingDataSet` will be delegated to the BAU …
=> Decrypt eIDAS unsigned assertions before creating a MatchingDataSet for the MSA

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/SamlResponseValidationException.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/conditions/AudienceRestrictionValidator.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/conditions/AudienceRestrictionValidatorMultipleEntityIdTests.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validators/conditions/AudienceRestrictionValidatorTest.java
This PR is part 1 of ~4 PRs that will form EID-1683. It:
- ...moves the `AudienceRestrictionValidator` into `verify-saml-libs`.
- ...updates the `AudienceRestrictionValidator` to accept 1 or more acceptable Entity Ids.
- ...changes behaviour of the `AudienceRestrictionValidator` to match against _any_ acceptable Entity Ids, falling back to default behaviour when only 1 is provided.
Subsequent PRs will:
- Adapt the MSA to accept more than 1 acceptable Entity Id through configuration, and use the new AudienceRestrictionValidator from saml-lib to validate the AudienceRestrictions in SAML Assertions (gracefully falling back to default behaviour if new configuration is not available).
- Adapt the VSP to accept more than 1 acceptable Entity Id through configuration, and use the new …
=> EID-1683 move AudienceRestrictionValidator to saml-lib

saml-lib/src/main/java/uk/gov/ida/saml/security/SecretKeyEncrypter.java
Update the type of `credentialFactory` field in `SecretKeyEncrypter` to be the interface `EncryptionCredentialResolver`. 
This will allow the **MSA** to construct a `SecretKeyEncrypter` with the `MetadataBackedEncryptionCredentialResolver` implementation.
The `SecretKeyEncrypter` is used by both `saml-engine` and `MSA` to encrypt and decrypt secret keys.
The Hub uses a `KeyStoreBackedEncryptionCredentialResolver` implementation of `EncryptionCredentialResolver` - this has been tested with the change proposed.
=> EID-1604 - Use EncryptionCredentialResolver as type for credentialFactory in SecretKeyEncrypter

saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/CountrySamlResponse.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/EncryptedAssertionKeys.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/UnsignedAssertionAttributeValue.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/impl/CountrySamlResponseImpl.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/impl/CountrySamlResponseMarshaller.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/impl/CountrySamlResponseUnmarshaller.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/impl/EncryptedAssertionKeysImpl.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/impl/EncryptedAssertionKeysMarshaller.java, saml-lib/src/main/java/uk/gov/ida/saml/core/extensions/eidas/impl/EncryptedAssertionKeysUnmarshaller.java, saml-lib/src/main/java/uk/gov/ida/saml/core/transformers/EidasUnsignedMatchingDatasetUnmarshaller.java, saml-lib/src/test/java/uk/gov/ida/saml/core/transformers/EidasUnsignedMatchingDatasetUnmarshallerTest.java
Introduce interface `UnsignedAssertionAttributeValue` which is extended by interfaces `CountrySamlResponse` and `EncryptedAssertionKeys`. This interface has
common methods for setting and getting the attribute’s value which means
less class-casting.
I've indicated where this code change is necessary in the comments below.
=> Make it easier to read values from eidas unsigned assertion attributes

saml-lib/src/main/java/uk/gov/ida/saml/deserializers/validators/ResponseSizeValidator.java, saml-lib/src/test/java/uk/gov/ida/saml/deserializers/validators/ResponseSizeValidatorTest.java
Create a close copy of the `ResponseSizeValidator` class in Hub.
It can then be used by both Hub and the MSA.
=> Add a ResponseSizeValidator to be used by Hub and MSA

saml-lib/src/main/java/uk/gov/ida/saml/core/transformers/EidasUnsignedMatchingDatasetUnmarshaller.java, saml-lib/src/main/java/uk/gov/ida/saml/security/EidasValidatorFactory.java, saml-lib/src/test/java/uk/gov/ida/saml/core/transformers/EidasUnsignedMatchingDatasetUnmarshallerTest.java
Use an `EidasValidatorFactory` in the `EidasUnsignedMatchingDatasetUnmarshaller` to validate the signature of the eidas saml response.
The signing certificate of the issuing country is used for signature validation, and is resolved from the supplied `MetadataResolverRepository`.
If the signature is invalid, an error will be logged and the MatchingDataset will be null.
=> Validate signature of eidas saml response using country metadata

build.gradle
verify-proxy-node baarfs in Travis because of snyk, the latest version of saml-libs will probably fix it but while I was checking I noticed that saml-libs could use the latest version of dropwizard and a newer version of verify-utils-libs.
=> BAU bump dropwizard version

saml-lib/src/main/java/uk/gov/ida/saml/core/validation/errors/BearerSubjectConfirmationValidationSpecification.java, saml-lib/src/main/java/uk/gov/ida/saml/core/validation/errors/SamlTransformationErrorFactory.java, saml-lib/src/test/java/uk/gov/ida/saml/core/validation/errors/SamlTransformationErrorFactoryTest.java
It's expected that we will sometimes receive expired assertions from IDPs, usually because the user spent too long - probably their session expired too.
https://govukverify.atlassian.net/browse/EID-1755
=> EID-1755 warn (not error) when processing expired assertions

saml-lib/src/main/java/uk/gov/ida/eidas/logging/EidasAttributesLogger.java, saml-lib/src/main/java/uk/gov/ida/eidas/logging/EidasResponseAttributesHashLogger.java, saml-lib/src/main/java/uk/gov/ida/eidas/logging/HubResponseTranslatorRequestInterface.java, saml-lib/src/main/java/uk/gov/ida/eidas/logging/TranslatedHubResponseInterface.java, saml-lib/src/main/java/uk/gov/ida/saml/core/transformers/MatchingDatasetBuilder.java, saml-lib/src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAddress.java, saml-lib/src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAttributes.java, saml-lib/src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingTransliterableAttribute.java, saml-lib/src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingVerifiableAttribute.java, saml-lib/src/main/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapper.java, saml-lib/src/test/java/uk/gov/ida/eidas/logging/EidasAttributesLoggerTest.java, saml-lib/src/test/java/uk/gov/ida/eidas/logging/EidasResponseAttributesHashLoggerTest.java, saml-lib/src/test/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingVerifiableAttributeBuilder.java, saml-lib/src/test/java/uk/gov/ida/verifyserviceprovider/mappers/MatchingDatasetToNonMatchingAttributesMapperTest.java
We log hashes of eIDAS attributes in the hub and the proxy-node. These
are then compared in Splunk to ensure nothing bad is happening.
The logic to do this was split over three places - the VSP, the
proxy-node and the hub. We want to consolidate the logic to ensure the
hashing is done in the same way.
The VSP extract the values from the attributes using the `MatchingDatasetToNonMatchingAttributesMapper`
which are then serialized and sent to the proxy-node using various
DTOs. This logic and DTOs have been imported to saml-lib. This allows
the hub to use the mapper to extract attributes directly from an
assertion using exactly the same logic as the VSP. The DTOs are now
available to the proxy-node to ensure that the serialized attributes are
de-serialized into the same objects.
There are …
=> EID-1762 Consolidate eIDAS hash logging

saml-lib/src/main/java/uk/gov/ida/eidas/logging/EidasAttributesLogger.java, saml-lib/src/main/java/uk/gov/ida/eidas/logging/EidasResponseAttributesHashLogger.java, saml-lib/src/main/java/uk/gov/ida/eidas/logging/HubResponseTranslatorRequestInterface.java, saml-lib/src/main/java/uk/gov/ida/eidas/logging/TranslatedHubResponseInterface.java, saml-lib/src/test/java/uk/gov/ida/eidas/logging/EidasAttributesLoggerTest.java
Saml-lib shouldn't need to know anything about the proxy-node and having
the interfaces tied it strongly to the proxy-node. We can instead
just pass in the objects we need from within the relevant objects.
=> EID-1762 Refactor out need for interfaces

saml-lib/src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingAttributes.java, saml-lib/src/main/java/uk/gov/ida/verifyserviceprovider/dto/NonMatchingVerifiableAttribute.java
These changes are to facilitate this proxy-node PR: https://github.com/alphagov/verify-proxy-node/pull/381
The class has been extended in the proxy-node and proxy-node specific
methods added. Making the fields protected allows that sub-class access
to them.
This also updates the way `isCurrent` of a
`NonMatchingVerifiableAttribute` is determined. This reflects recent
work done in the proxy-node: https://github.com/alphagov/verify-proxy-node/pull/364/file
=> EID-1762 Refactor NonMatchingAttributes fields

build.gradle, saml-lib/src/test/java/uk/gov/ida/eidas/logging/EidasResponseAttributesHashLoggerTest.java
This change replaces org.apache.commons.lang.reflect.FieldUtils with org.apache.commons.lang3.reflect.FieldUtils because org.apache.commons.lang.reflect.FieldUtils does not exist. It updates AssertJ and Mockito libraries to the latest versions.
Author: @adityapahuja
=> BAU: Use latest verison of common-test-utils lib

.travis.yml
The structure of json at https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest has changed.
We use this document to find a download url for a required codacy coverage jar.
Update the jq search for this download url.
Taken from Hub: https://github.com/alphagov/verify-hub/pull/415/commits/2509303e344dca60f5623abfb0dd5aa9cf68c405
=> Correct jq to fetch codacy coverage jar

publish.gradle
Bintray is the source of truth now.
Bintray is made available via whitelisted-repos on artifactory, so we
still pull dependencies down using artifactory, but we only need to
push dependencies to bintray.
=> Stop publishing to artifactory

build.gradle, saml-lib/src/test/java/uk/gov/ida/saml/metadata/CertificateChainValidationFilterTest.java, saml-lib/src/test/java/uk/gov/ida/saml/metadata/PKIXSignatureValidationFilterProviderTest.java
Use the latest verify-dev-pki which has test elliptic curve certs and keys.
Commons IOUtils no longer on classpath, so remove use and create an inputstream directly.
=> EID-1944 latest verify-dev-pki

saml-lib/src/main/java/uk/gov/ida/eidas/logging/EidasAuthnResponseAttributesHashLogger.java, saml-lib/src/main/java/uk/gov/ida/eidas/logging/HashableResponseAttributes.java, saml-lib/src/test/java/uk/gov/ida/eidas/logging/EidasAuthnResponseAttributesHashBuilderTest.java, saml-lib/src/test/java/uk/gov/ida/eidas/logging/EidasAuthnResponseAttributesHashLoggerTest.java, saml-lib/src/test/java/uk/gov/ida/eidas/logging/HashableResponseAttributesTest.java
To mitigate against fraud, we log the hash of user attributes for an eIDAS journey in the Hub and in Proxy Node Translator. If these hashes do do match there may have been tampering of identities.
Currently, the user’s PID from the IDP is included in the hash. However, as we need to support “transient” PIDs for eIDAS, it means that we will send a different PID back to the requesting the country than what we received from the IDP. This means that we’ll be sending an identity with a different hash to what we had logged, which means that we won’t be able to tell if the identity has been tampered with in case there needs to be a fraud investigation.
To mitigate this, we will use the Proxy Node request ID generated by the VSP. This is the only common is we can use since it’s available both in …
=> EID-1980 log Hub request id instead of pid from IDP

saml-lib/src/main/java/uk/gov/ida/saml/security/validators/ValidatedResponse.java
We want to evaluate the namespaces on a valid reponse for PR https://github.com/alphagov/verify-hub/pull/454.
This provides that non null set of namespaces.
=> EID-1977 get namespaces on a validated response

saml-lib/src/main/java/uk/gov/ida/Base64.java, saml-lib/src/test/java/uk/gov/ida/Base64Test.java
The Verify / Proxy Node uses many of the different available libraries for Base64 encoding including `import org.glassfish.jersey.internal.util.Base64` which is a barrier to upgrading to Dropwizard 2.
This provides a facade to the java.util implementation so that the codebase can have one true base64 to rule them all.  Unfortunately saml-lib itself does some fairly funky stuff that includes injecting its own (overcooked?) base64 implementation so this immediately has a limitation (or rather there are more pressing things to do and I thought it would be much simpler) so that ironically, saml-lib doesn't use the base64 lib it provides at the moment.
=> BAU - Utility class to encapsulate Base64 actions

build.gradle
It includes constants for the new CAs so they can be used easily in
consuming projects.
=> BAU: Bump dev-pki version to 1.2.0-16

saml-lib/src/main/java/uk/gov/ida/saml/metadata/TrustStoreBackedMetadataConfiguration.java
This is to allow a default trust store configuration to be used in the
MSA. See this PR for details: https://github.com/alphagov/verify-matching-service-adapter/pull/159
=> HUB-697: Remove `NotNull` from TrustStoreBackedMetadataConfiguration

saml-lib/src/main/java/uk/gov/ida/saml/metadata/EidasMetadataConfiguration.java
This changes the period that the trust-anchors are polled from 1 hour to
5 minutes. If a new trust-anchor is published it means that something is
already probably broken and we don't want to wait an hour for it. One
request every 5 minutes is not excessive.
Also, changing the default will mean that there's no need to update
config files for the MSA/VSP or the hub.
=> BAU: Decrease trustAnchorMaxRefreshDelay

publish.gradle
`project.description` was empty resulting in the description not being
added to the POM, and so Sonatype refusing to close the repo.
=> HUB-866: Ensure published libs have description

.travis.yml, build.gradle
This uses the maven central for public builds, and bumps versions to
make sure it's being used rather than bintray.
This requires the Java version to move from 8 to 11, as the only version
of rest-utils and common-utils available from maven central is compiled
with Java 11.
=> HUB-913: Pull from maven central

.travis.yml, build.gradle
The MSA and the VSP need to stay compatible with Java 8 for the sake of
services.
saml-lib is a direct dependency of the MSA and the VSP.
saml-lib needs to be published with Java 8 byte code or the MSA and the
VSP won't be able to use it.
This pulls in version 396 of the utils libs, which have also just been
downgraded to Java 8 for the same reason.
Also removes an old and unloved plugin.
=> HUB-912: Downgrade to Java 8

build.gradle, saml-lib/src/main/java/uk/gov/ida/saml/metadata/MetadataRefreshTask.java, saml-test/src/main/java/uk/gov/ida/saml/core/test/OpenSAMLExtension.java
**Can't be merged before: https://github.com/alphagov/verify-utils-libs/pull/63, https://github.com/alphagov/verify-test-utils/pull/19,**
This bumps dropwizard to 2, for use by the hub.
It bumps opensaml. The old version was dependant on an old version of
apach httpclient which was causing a class path clash in the hub.
It pulls in updated versions of our utils libraries - these are currently
set to SNAPSHOT as there are PR's on these libs waiting to be merged.
It also adds a new class, `OpenSAMLExtension`. This is a junit 5 extension
which does the job of bootstrapping Ida SAML. This is used extensively
in the hub tests.
=> HUB-942: Dropwizard -> 2, OpenSAML -> 3.4.6

saml-lib/src/main/java/uk/gov/ida/saml/security/signature/OutgoingKeySignatureTrustEngine.java, saml-lib/src/test/java/uk/gov/ida/saml/security/signature/OutgoingKeySignatureTrustEngineTest.java
As a developer I want to know that the Hub is validating SAML responses using the "outgoing" SAML signing certificate, so that I know it is not safe to remove this certificate from metadata.
As part of the IDP SAML Certificate process, a new signing certificate is introduced to metadata for that IDP.
The "outgoing" cert is set to the "backup" position, and the Hub will validate SAML responses using the new cert, then the outgoing cert.
When there are two certs used for validation, and we successfully use the outgoing cert to validate, we can be sure that the IDP has not yet started using their new signing key. In this condition, set a Prometheus counter.
=> HUB-1055: Add metric on IDP SAML response
